export interface Aets {
   
    _id: number,
    status: string,
    tipo: string,
    ghre?: string,
    expostos?: number,
    setor?: string,
    postoDeTrabalho?: string,
    dataAvaliacao?: string,
    nomeAnalista?: string,
    entrevista?: string,
    afastamento?: boolean,
    remanejamento?: boolean,

    descricao?: string,

    checkBio1?: boolean,
    checkBio2?: boolean,
    checkBio3?: boolean,
    checkBio4?: boolean,
    checkBio5?: boolean,
    checkBio6?: boolean,
    checkBio7?: boolean,
    checkBio8?: boolean,
    checkBio9?: boolean,
    checkBio10?: boolean,
    checkBio11?: boolean,
    checkBio12?: boolean,
    checkBio13?: boolean,
    checkBio14?: boolean,
    checkBio15?: boolean,
    checkBio16?: boolean,
    checkBio17?: boolean,
    checkBio18?: boolean,
    checkBio19?: boolean,
    checkBio20?: boolean,
    checkBio21?: boolean,

    checkMob1?: boolean,
    checkMob2?: boolean,
    checkMob3?: boolean,
    checkMob4?: boolean,
    checkMob5?: boolean,
    checkMob6?: boolean,
    checkMob7?: boolean,
    checkMob8?: boolean,
    checkMob9?: boolean,
    checkMob10?: boolean,

    checkOrg1?: boolean,
    checkOrg2?: boolean,
    checkOrg3?: boolean,
    checkOrg4?: boolean,
    checkOrg5?: boolean,
    checkOrg6?: boolean,
    checkOrg7?: boolean,
    checkOrg8?: boolean,
    checkOrg9?: boolean,
    checkOrg10?: boolean,
    checkOrg11?: boolean,

    checkAmb1?: boolean,
    checkAmb2?: boolean,
    checkAmb3?: boolean,
    checkAmb4?: boolean,
    checkAmb5?: boolean,
    checkAmb6?: boolean,
    checkAmb7?: boolean,
    checkAmb8?: boolean,
    checkAmb9?: boolean,

    checkPsc1?: boolean,
    checkPsc2?: boolean,
    checkPsc3?: boolean,
    checkPsc4?: boolean,
    checkPsc5?: boolean,
    checkPsc6?: boolean,
    checkPsc7?: boolean,
    checkPsc8?: boolean,
    checkPsc9?: boolean,
    checkPsc10?: boolean,
    checkPsc11?: boolean,
    checkPsc12?: boolean,

}
